### ISSUE TITLE
Initialized sliders overwrites default configurations.

### ISSUE THREAD

**Issue by JoonasToroi** [MyCashflow/MyCashflow-Barebones-Theme#3]
Slider configurations in custom.js are overwriten by initialized sliders. This bug affects all the slider settings defined in custom.js.

For example if you place the frontpage `banner-wide` slider after the top sellers `grid-list` slider, the `banner-wide` slider will get responsive configuration from the `grid-list` settings, not form defaults.

Quick fix is to set a `responsive : null` for the `banner-wide` slider. Still, it would be nice if the intialized sliders wouldn't affect the default values.

**Comment by jukkakoskinen** [comment]
Hi Joonas, and thanks for the comprehensive bug report – I'll look into this.

**Comment by jukkakoskinen** [comment]
This should be fixed in c8ba6be088e2978f7e781855858265c92e8ed69e.
